export enum Topics {
  LEAGUE_IMPORT_REQUEST = 'LEAGUE_IMPORT_REQUEST',
  LEAGUE_IMPORT_PAYLOAD = 'LEAGUE_IMPORT_PAYLOAD',
  LEAGUE_QUERY_REQUEST = 'LEAGUE_QUERY_REQUEST',
  LEAGUE_QUERY_RESPONSE = 'LEAGUE_QUERY_RESPONSE'
}